### PR TITLE
Add TorchScript version 

### PR DESCRIPTION
**Pull request by yarkable**
Hi, I just did something that can export PyTorch model to TorchScript version

1. Add modified MODNet that satisfies TorchScript version 
2. Modify MobileNetV2 (Due to torch.jit doesn't support lambda expression)
3. Upload an exported TorchScript model using official pretrain model (See README.md for detail)

### CODE REVIEW

**Comment by ZHKKKe** [comment]
Hi, thanks for your contributions! I will test the code and merge it next week. Then I will give you a feedback.

**Comment by yarkable** [comment]
Thanks a lot !

**Comment by ZHKKKe** [comment]
Hi, I have tried to merge you branch. However, it seems that the code will affect some other demos. Therefore, I reversed it.
Could you start a new pull requests to the branch `develop`?
In this way, I can process it before merge it to `master`. Thanks.

**Comment by yarkable** [comment]
No problem.

**Pull request merged**
