### PR TITLE
MODNet docker container

### PR DESCRIPTION
**Pull request by nahidalam**
Added link to MODNet docker container in the community section

### CODE REVIEW

**Comment by ZHKKKe** [comment]
Hi, thanks for your pull request. However, I cannot open the repo link. Is it still works now?

**Comment by nahidalam** [comment]
@ZHKKKe sorry I found some bugs there so closed this PR. I will create a new PR with updates

**Comment by ZHKKKe** [comment]
Thanks. Looking forward for your update. :)

**Comment by nahidalam** [comment]
@ZHKKKe please check PR#171 :)

**Pull request closed without merging**
